// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: v2/user_v2.proto

package userv2pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserV2_GetAllUsers_FullMethodName = "/userv2pb.UserV2/GetAllUsers"
)

// UserV2Client is the client API for UserV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserV2Client interface {
	GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error)
}

type userV2Client struct {
	cc grpc.ClientConnInterface
}

func NewUserV2Client(cc grpc.ClientConnInterface) UserV2Client {
	return &userV2Client{cc}
}

func (c *userV2Client) GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUsersResponse)
	err := c.cc.Invoke(ctx, UserV2_GetAllUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserV2Server is the server API for UserV2 service.
// All implementations must embed UnimplementedUserV2Server
// for forward compatibility.
type UserV2Server interface {
	GetAllUsers(context.Context, *GetAllUsersRequest) (*GetAllUsersResponse, error)
	mustEmbedUnimplementedUserV2Server()
}

// UnimplementedUserV2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserV2Server struct{}

func (UnimplementedUserV2Server) GetAllUsers(context.Context, *GetAllUsersRequest) (*GetAllUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (UnimplementedUserV2Server) mustEmbedUnimplementedUserV2Server() {}
func (UnimplementedUserV2Server) testEmbeddedByValue()                {}

// UnsafeUserV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserV2Server will
// result in compilation errors.
type UnsafeUserV2Server interface {
	mustEmbedUnimplementedUserV2Server()
}

func RegisterUserV2Server(s grpc.ServiceRegistrar, srv UserV2Server) {
	// If the following call pancis, it indicates UnimplementedUserV2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserV2_ServiceDesc, srv)
}

func _UserV2_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserV2Server).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserV2_GetAllUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserV2Server).GetAllUsers(ctx, req.(*GetAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserV2_ServiceDesc is the grpc.ServiceDesc for UserV2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserV2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userv2pb.UserV2",
	HandlerType: (*UserV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllUsers",
			Handler:    _UserV2_GetAllUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/user_v2.proto",
}
