// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: v2/rpc_v2.proto

package rpcv2pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rpcv2_RpcInfoUpdate_FullMethodName     = "/rpcv2pb.Rpcv2/RpcInfoUpdate"
	Rpcv2_GetRpcInfo_FullMethodName        = "/rpcv2pb.Rpcv2/GetRpcInfo"
	Rpcv2_GetAllRpcInfoList_FullMethodName = "/rpcv2pb.Rpcv2/GetAllRpcInfoList"
)

// Rpcv2Client is the client API for Rpcv2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Rpcv2Client interface {
	// RpcInfoUpdate Rpc设置
	RpcInfoUpdate(ctx context.Context, in *RpcInfoUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	// GetRpcInfo 获取Rpc设置
	GetRpcInfo(ctx context.Context, in *GetRpcInfoRequest, opts ...grpc.CallOption) (*GetRpcInfoResponse, error)
	// GetRpcInfoList 获取Rpc设置列表（All）
	GetAllRpcInfoList(ctx context.Context, in *GetAllRpcInfoListRequest, opts ...grpc.CallOption) (*GetAllRpcInfoListResponse, error)
}

type rpcv2Client struct {
	cc grpc.ClientConnInterface
}

func NewRpcv2Client(cc grpc.ClientConnInterface) Rpcv2Client {
	return &rpcv2Client{cc}
}

func (c *rpcv2Client) RpcInfoUpdate(ctx context.Context, in *RpcInfoUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Rpcv2_RpcInfoUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcv2Client) GetRpcInfo(ctx context.Context, in *GetRpcInfoRequest, opts ...grpc.CallOption) (*GetRpcInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRpcInfoResponse)
	err := c.cc.Invoke(ctx, Rpcv2_GetRpcInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcv2Client) GetAllRpcInfoList(ctx context.Context, in *GetAllRpcInfoListRequest, opts ...grpc.CallOption) (*GetAllRpcInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllRpcInfoListResponse)
	err := c.cc.Invoke(ctx, Rpcv2_GetAllRpcInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Rpcv2Server is the server API for Rpcv2 service.
// All implementations must embed UnimplementedRpcv2Server
// for forward compatibility.
type Rpcv2Server interface {
	// RpcInfoUpdate Rpc设置
	RpcInfoUpdate(context.Context, *RpcInfoUpdateRequest) (*Empty, error)
	// GetRpcInfo 获取Rpc设置
	GetRpcInfo(context.Context, *GetRpcInfoRequest) (*GetRpcInfoResponse, error)
	// GetRpcInfoList 获取Rpc设置列表（All）
	GetAllRpcInfoList(context.Context, *GetAllRpcInfoListRequest) (*GetAllRpcInfoListResponse, error)
	mustEmbedUnimplementedRpcv2Server()
}

// UnimplementedRpcv2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcv2Server struct{}

func (UnimplementedRpcv2Server) RpcInfoUpdate(context.Context, *RpcInfoUpdateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RpcInfoUpdate not implemented")
}
func (UnimplementedRpcv2Server) GetRpcInfo(context.Context, *GetRpcInfoRequest) (*GetRpcInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRpcInfo not implemented")
}
func (UnimplementedRpcv2Server) GetAllRpcInfoList(context.Context, *GetAllRpcInfoListRequest) (*GetAllRpcInfoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRpcInfoList not implemented")
}
func (UnimplementedRpcv2Server) mustEmbedUnimplementedRpcv2Server() {}
func (UnimplementedRpcv2Server) testEmbeddedByValue()               {}

// UnsafeRpcv2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Rpcv2Server will
// result in compilation errors.
type UnsafeRpcv2Server interface {
	mustEmbedUnimplementedRpcv2Server()
}

func RegisterRpcv2Server(s grpc.ServiceRegistrar, srv Rpcv2Server) {
	// If the following call pancis, it indicates UnimplementedRpcv2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rpcv2_ServiceDesc, srv)
}

func _Rpcv2_RpcInfoUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcInfoUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rpcv2Server).RpcInfoUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpcv2_RpcInfoUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rpcv2Server).RpcInfoUpdate(ctx, req.(*RpcInfoUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpcv2_GetRpcInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRpcInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rpcv2Server).GetRpcInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpcv2_GetRpcInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rpcv2Server).GetRpcInfo(ctx, req.(*GetRpcInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpcv2_GetAllRpcInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRpcInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rpcv2Server).GetAllRpcInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpcv2_GetAllRpcInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rpcv2Server).GetAllRpcInfoList(ctx, req.(*GetAllRpcInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rpcv2_ServiceDesc is the grpc.ServiceDesc for Rpcv2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rpcv2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcv2pb.Rpcv2",
	HandlerType: (*Rpcv2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcInfoUpdate",
			Handler:    _Rpcv2_RpcInfoUpdate_Handler,
		},
		{
			MethodName: "GetRpcInfo",
			Handler:    _Rpcv2_GetRpcInfo_Handler,
		},
		{
			MethodName: "GetAllRpcInfoList",
			Handler:    _Rpcv2_GetAllRpcInfoList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/rpc_v2.proto",
}
