// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: v1/rpc.proto

package rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rpc_RpcInfoUpdate_FullMethodName     = "/rpcpb.Rpc/RpcInfoUpdate"
	Rpc_GetRpcInfo_FullMethodName        = "/rpcpb.Rpc/GetRpcInfo"
	Rpc_GetAllRpcInfoList_FullMethodName = "/rpcpb.Rpc/GetAllRpcInfoList"
)

// RpcClient is the client API for Rpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcClient interface {
	// RpcInfoUpdate Rpc设置
	RpcInfoUpdate(ctx context.Context, in *RpcInfoUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	// GetRpcInfo 获取Rpc设置
	GetRpcInfo(ctx context.Context, in *GetRpcInfoRequest, opts ...grpc.CallOption) (*GetRpcInfoResponse, error)
	// GetRpcInfoList 获取Rpc设置列表（All）
	GetAllRpcInfoList(ctx context.Context, in *GetAllRpcInfoListRequest, opts ...grpc.CallOption) (*GetRpcInfoListResponse, error)
}

type rpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcClient(cc grpc.ClientConnInterface) RpcClient {
	return &rpcClient{cc}
}

func (c *rpcClient) RpcInfoUpdate(ctx context.Context, in *RpcInfoUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Rpc_RpcInfoUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) GetRpcInfo(ctx context.Context, in *GetRpcInfoRequest, opts ...grpc.CallOption) (*GetRpcInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRpcInfoResponse)
	err := c.cc.Invoke(ctx, Rpc_GetRpcInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) GetAllRpcInfoList(ctx context.Context, in *GetAllRpcInfoListRequest, opts ...grpc.CallOption) (*GetRpcInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRpcInfoListResponse)
	err := c.cc.Invoke(ctx, Rpc_GetAllRpcInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcServer is the server API for Rpc service.
// All implementations must embed UnimplementedRpcServer
// for forward compatibility.
type RpcServer interface {
	// RpcInfoUpdate Rpc设置
	RpcInfoUpdate(context.Context, *RpcInfoUpdateRequest) (*Empty, error)
	// GetRpcInfo 获取Rpc设置
	GetRpcInfo(context.Context, *GetRpcInfoRequest) (*GetRpcInfoResponse, error)
	// GetRpcInfoList 获取Rpc设置列表（All）
	GetAllRpcInfoList(context.Context, *GetAllRpcInfoListRequest) (*GetRpcInfoListResponse, error)
	mustEmbedUnimplementedRpcServer()
}

// UnimplementedRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcServer struct{}

func (UnimplementedRpcServer) RpcInfoUpdate(context.Context, *RpcInfoUpdateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RpcInfoUpdate not implemented")
}
func (UnimplementedRpcServer) GetRpcInfo(context.Context, *GetRpcInfoRequest) (*GetRpcInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRpcInfo not implemented")
}
func (UnimplementedRpcServer) GetAllRpcInfoList(context.Context, *GetAllRpcInfoListRequest) (*GetRpcInfoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRpcInfoList not implemented")
}
func (UnimplementedRpcServer) mustEmbedUnimplementedRpcServer() {}
func (UnimplementedRpcServer) testEmbeddedByValue()             {}

// UnsafeRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcServer will
// result in compilation errors.
type UnsafeRpcServer interface {
	mustEmbedUnimplementedRpcServer()
}

func RegisterRpcServer(s grpc.ServiceRegistrar, srv RpcServer) {
	// If the following call pancis, it indicates UnimplementedRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rpc_ServiceDesc, srv)
}

func _Rpc_RpcInfoUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcInfoUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).RpcInfoUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpc_RpcInfoUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).RpcInfoUpdate(ctx, req.(*RpcInfoUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_GetRpcInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRpcInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).GetRpcInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpc_GetRpcInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).GetRpcInfo(ctx, req.(*GetRpcInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_GetAllRpcInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRpcInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).GetAllRpcInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpc_GetAllRpcInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).GetAllRpcInfoList(ctx, req.(*GetAllRpcInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rpc_ServiceDesc is the grpc.ServiceDesc for Rpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.Rpc",
	HandlerType: (*RpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcInfoUpdate",
			Handler:    _Rpc_RpcInfoUpdate_Handler,
		},
		{
			MethodName: "GetRpcInfo",
			Handler:    _Rpc_GetRpcInfo_Handler,
		},
		{
			MethodName: "GetAllRpcInfoList",
			Handler:    _Rpc_GetAllRpcInfoList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/rpc.proto",
}
