// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: rpc.proto

package rpc

import (
	"context"

	"github.com/ethereum/go-ethereum/portal/zrpc_client/model/rpc_portal/pb/rpcpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty                    = rpcpb.Empty
	GetAllRpcInfoListRequest = rpcpb.GetAllRpcInfoListRequest
	GetRpcInfoListResponse   = rpcpb.GetRpcInfoListResponse
	GetRpcInfoRequest        = rpcpb.GetRpcInfoRequest
	GetRpcInfoResponse       = rpcpb.GetRpcInfoResponse
	RpcInfoUpdateRequest     = rpcpb.RpcInfoUpdateRequest

	Rpc interface {
		// RpcInfoUpdate Rpc设置
		RpcInfoUpdate(ctx context.Context, in *RpcInfoUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		// GetRpcInfo 获取Rpc设置
		GetRpcInfo(ctx context.Context, in *GetRpcInfoRequest, opts ...grpc.CallOption) (*GetRpcInfoResponse, error)
		// GetRpcInfoList 获取Rpc设置列表（All）
		GetAllRpcInfoList(ctx context.Context, in *GetAllRpcInfoListRequest, opts ...grpc.CallOption) (*GetRpcInfoListResponse, error)
	}

	defaultRpc struct {
		cli zrpc.Client
	}
)

func NewRpc(cli zrpc.Client) Rpc {
	return &defaultRpc{
		cli: cli,
	}
}

// RpcInfoUpdate Rpc设置
func (m *defaultRpc) RpcInfoUpdate(ctx context.Context, in *RpcInfoUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := rpcpb.NewRpcClient(m.cli.Conn())
	return client.RpcInfoUpdate(ctx, in, opts...)
}

// GetRpcInfo 获取Rpc设置
func (m *defaultRpc) GetRpcInfo(ctx context.Context, in *GetRpcInfoRequest, opts ...grpc.CallOption) (*GetRpcInfoResponse, error) {
	client := rpcpb.NewRpcClient(m.cli.Conn())
	return client.GetRpcInfo(ctx, in, opts...)
}

// GetRpcInfoList 获取Rpc设置列表（All）
func (m *defaultRpc) GetAllRpcInfoList(ctx context.Context, in *GetAllRpcInfoListRequest, opts ...grpc.CallOption) (*GetRpcInfoListResponse, error) {
	client := rpcpb.NewRpcClient(m.cli.Conn())
	return client.GetAllRpcInfoList(ctx, in, opts...)
}
